# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    ruby_task_helper: "https://github.com/puppetlabs/puppetlabs-ruby_task_helper.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
